### ISSUE TITLE
Send screen 6.0

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#467]
Design: https://zpl.io/Vq3ykp5

1) Remove "advanced", "tags", "edit address" and make mobile features equal to desktop.

2) Remove "Fee" block.

3) Make each section as block with non-transparent bg https://zpl.io/2p317Mj
![image](https://user-images.githubusercontent.com/47353570/114764114-3a97fc80-9d6c-11eb-8244-1a8652cd0e51.png)

4) Change "more details" to "address details" and "add all" to "add max" https://zpl.io/ad3xYX5
![image](https://user-images.githubusercontent.com/47353570/114764203-526f8080-9d6c-11eb-97e3-d57959c3d3dd.png)

5) Regular(offline) address https://zpl.io/ad3xYX5
![image](https://user-images.githubusercontent.com/47353570/114764351-83e84c00-9d6c-11eb-993b-53b636885514.png)

6) Max Privacy address. There is no "Transaction type" block https://zpl.io/2v3MA6J 
![image](https://user-images.githubusercontent.com/47353570/114764375-8c408700-9d6c-11eb-99cf-8e1d63398ea5.png)

7) Address details https://zpl.io/Vx3mQ6x
![image](https://user-images.githubusercontent.com/47353570/114775974-99fd0900-9d7a-11eb-987d-3bfe1ad1f716.png)

8) Confirmation screen https://zpl.io/29mqzKe
![image](https://user-images.githubusercontent.com/47353570/114775950-923d6480-9d7a-11eb-8fa6-8b7ef9198e87.png)

9) Please make buttons "Send", "Cope and close"and "Next" the same wight.
![image](https://user-images.githubusercontent.com/47353570/114775917-88b3fc80-9d7a-11eb-92e0-c39c94726310.png)

10) Make main title in white color and sub-titles in grey color
![image](https://user-images.githubusercontent.com/47353570/114764951-3b7d5e00-9d6d-11eb-95d6-6957dbcdfba8.png)

**Comment by dariatarakanova** [comment]
the same fixes as on android #531

1) Correct text for offline transaction is "Min transaction fee to send offline transaction is 0.01 BEAM." https://zpl.io/aME8AXm

2) Change "Regular address" https://zpl.io/2jNqvZx to "Regular online-only address" and "Regular offline-only address" https://zpl.io/25PzGE8
![image](https://user-images.githubusercontent.com/47353570/120224196-a87c8280-c24b-11eb-8093-09ef71924701.png)

**Comment by kazaryan-t** [comment]
1. In the _Transaction Info_ field put the conjunction **OR** instead of the comma between words **address** and **name**.
![Фотографии 2021-06-01 16 24 07](https://user-images.githubusercontent.com/68247034/120330687-b850a100-c2f5-11eb-8a00-9dd431037589.png)

2. Make letter spacing as in the design in the word **BEAM** near to the amount field.
![6 0_send-max-privacy-contact - 02 iOS Wallet - Zep](https://user-images.githubusercontent.com/68247034/120330912-f1891100-c2f5-11eb-96bc-bbfb610ef01a.png)
![Фотографии 2021-06-01 16 25 34](https://user-images.githubusercontent.com/68247034/120330916-f221a780-c2f5-11eb-94b8-d829ba1887cf.png)

3. The word **COMMENT** should be written in white color.
![IMG_0163 PNG ‎- Фотографии 2021-06-01 16 27 09](https://user-images.githubusercontent.com/68247034/120331058-11b8d000-c2f6-11eb-9a0c-bd8a132d9391.png)

4. The comment tab does not open. (screen recording attached)

https://user-images.githubusercontent.com/68247034/120331123-209f8280-c2f6-11eb-94af-ce7efa292dc5.MP4

5. Change the text for Max Privacy address transactions.
The text should be:

**Max Privacy transaction can last at most 72 hours.
Min transaction fee to send Max privacy coins is 0.01 BEAM.**
6. Put the text for Max privacy transactions in the center of the screen and make the font size a bit bigger as in the design.
![IMG_0166](https://user-images.githubusercontent.com/68247034/120331483-7d9b3880-c2f6-11eb-9e28-0e2dcda570e2.PNG)

7. Place text about min transaction fee as in the design.
8. When the user selects a max privacy address from contacts in the Transaction field, on the confirmation screen, the contact's name is not displayed.

https://user-images.githubusercontent.com/68247034/120332713-ad970b80-c2f7-11eb-92b9-f7ab7a8808f1.MP4

9. Change the color of the contact's name and his address on the Confirmation screen and the contact's name should appear first and under the contact's name goes the contact's address.

10. Implement changes described in the previous comment. 
https://github.com/BeamMW/ios-wallet/issues/467#issuecomment-851601149

**Comment by kazaryan-t** [comment]
1. № 3 not fixed - The word COMMENT should be written in white color.
![IMG_0163 PNG ‎- Фотографии 2021-06-01 16 27 09](https://user-images.githubusercontent.com/68247034/120615280-c66f0080-c460-11eb-8511-40cfb15c7205.png)

2. The bug described in the https://github.com/BeamMW/ios-wallet/issues/478#issuecomment-853079284 not fixed.

https://user-images.githubusercontent.com/68247034/120615463-fb7b5300-c460-11eb-9bc7-f5308f6727ec.MP4

3. Make smaller the font size for the Transaction info field, the whole text should fit in the field

![IMG_0176](https://user-images.githubusercontent.com/68247034/120617957-44cca200-c463-11eb-8fc2-ac3296a62512.PNG)

4. Add dots after _"Regular online-only address"_ and _"Regular offline-only address"_ text

![IMG_0179](https://user-images.githubusercontent.com/68247034/120619171-6aa67680-c464-11eb-9273-08c28443d469.PNG)
![IMG_0181](https://user-images.githubusercontent.com/68247034/120619177-6b3f0d00-c464-11eb-9f8d-b053133feeeb.PNG)

Designs: **regular** - https://zpl.io/2jNqvZx, **offline** - https://zpl.io/25PzGE8

**Comment by Denis-Asipenko** [comment]
checked
