### ISSUE TITLE
Receive and Send screen: currency selection

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#489]
Please work only on points mentioned in this task. Design for Send and receive screens will be changed later in another task.

1)Dropdown coin's list on receive screen. https://zpl.io/bleZxPP
![image](https://user-images.githubusercontent.com/47353570/126526189-f50e2b40-4bad-4495-acf3-8e00e4b1693d.png)

2) Arrow position when list is closed
![image](https://user-images.githubusercontent.com/47353570/126526261-b35be426-e1fb-4a5c-b6a0-28c1ffb55d58.png)

2.1) Arrow position when list is open
![image](https://user-images.githubusercontent.com/47353570/126526554-76c775a0-0372-439c-be74-d560350f4077.png)

3) Same flow for Send screen https://zpl.io/a7p5M3W
![image](https://user-images.githubusercontent.com/47353570/126526553-abed955c-e2bf-4059-b8de-3bcf01b15a0d.png)

**Comment by AndreyDyakonov** [comment]
If we click arrow near "BEAM" then instead of a drop-down coin's list opened new window with available coins

![photo_2021-07-27_12-25-10](https://user-images.githubusercontent.com/85252690/127132208-1ee81106-ae01-491e-a35a-f318d7d564ac.jpg)

![photo_2021-07-27_12-25-22](https://user-images.githubusercontent.com/85252690/127132223-dc3bb8cf-9793-4b5e-b8e3-8d9fa474eabd.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
