### ISSUE TITLE
Redesign amount presentation of long numbers

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#84]
We should change displaying units of our currency on all screens. (Wallet, Send, UTXO)

We left one word "Amount" in the header 
In cells we write Beam or Groth next to amount

**Comment by kaminskyelina** [comment]
Sasha's request - Show groths instead of beams when amount is less than 10 000 groths
to be same solution in Android and iOS

**Comment by kaminskyelina** [comment]
**Description**
In mobile wallets, once the application goes to the background or in screen off - the process goes sleep. In this case transactions cannot handled

Awake once in 30 min and pop-up messages is not a guarantee, since after some time in screen off also the internet disconnects

Sasha suggests to design user alert in the wallet that ask to stay online

**Comment by kaminskyelina** [comment]
**Options that we discussed about:**

Show groths instead of beams when amount is less than 10 000 groth
Separate groths
Present Sending and receiving in different lines
Take Maturing out to Available Balance section
Rounding

**Comment by kaminskyelina** [comment]
![IMAGE 2019-04-01 18:49:41](https://user-images.githubusercontent.com/45590119/55341220-eab0aa80-54ae-11e9-9eee-aae0cc2925b6.jpg)

**Comment by alexandrashelenkova** [comment]
new design is here zpl.io/adzNvKK

**Comment by Denis-Asipenko** [comment]
invalid
