### ISSUE TITLE
Settings: Connect to specific node from mobile wallet

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#98]

**Comment by alexandrashelenkova** [comment]
screens are here
zpl.io/25OMeK8
zpl.io/V0L0Dow

**Comment by alexandrashelenkova** [comment]
Setting screen updated, added one more screen here zpl.io/2pvneqQ

**Comment by Denis-Asipenko** [comment]
1. Why IP and port in two different lines? @alexandrashelenkova 
2. I think we need to solve node or peer and display one option. @alexandrashelenkova 
![image](https://user-images.githubusercontent.com/45556620/56429423-76a63d00-62cb-11e9-94b0-e8f67d654cdf.png)
3. User сan not save settings if delete port or IP or delete both. @DenisDemyanko 
4. Must be IP instead of Address. @DenisDemyanko 
5. Make the words brighter. @DenisDemyanko 
![image](https://user-images.githubusercontent.com/45556620/56429329-2dee8400-62cb-11e9-9b16-cc52b8080a95.png)

**Comment by alexandrashelenkova** [comment]
1. @sasha-abramovich asked to make two fields in commets in zeplin
2. Let's keep "node", I will update screens in zeplin later
3. It gonna be default alert same as incompatible node, I will add screen later too, but I think that one might be done without actual design for now?
4,5. Screen for testnet should be same as for mainnet in design (just different background color). So it should be ip:port in screen title, and text in fields should be white

**Comment by Denis-Asipenko** [comment]
checked
